### ISSUE TITLE
Enhancements/additions

### ISSUE THREAD

**Issue by Udaldor** [Dynious/RefinedRelocation#170]
Add a new feature to the extraction module (or an advanced one) that allows for more options. One option could be a "per redstone signal" extraction feature, allowing the module to extract one stack per signal. Another one could be an option allowing you to set how big stacks should be.

EDIT: will be adding comments with suggestions.

**Comment by blay09** [comment]
Extraction modules seem to have the per-pulse feature by now.
The balance module you speak of can be achieved by using stock modules, which is also more intuitive than color coding chests and having it compare their contents.
