### ISSUE TITLE
(Feature Request) Support for Dimensional Storage Mod

### ISSUE THREAD

**Issue by Vaygrim** [Dynious/RefinedRelocation#221]
Dimensional Storage : http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2104639-dimstorage

Dynious, would it at all be possible to put in support for Dimensional Storage? I'd love to see it integrated into Refined Relocation, so DimStorage chests could be turned into sorting chests / etc. Let me know, thanks!

**Comment by blay09** [comment]
If support for Dimensional Storage is still desired, please bring this issue over to their tracker and ask them nicely to add Refined Relocation sorting versions of their storage blocks using RR's API.

Alternatively, use the Sorting Interface and wait for #306 to make the Sorting Interface work for input items too.
