### ISSUE TITLE
Missing NBT data for wireless and advanced filter blocks.

### ISSUE THREAD

**Issue by NolanSyKinsley** [Dynious/RefinedRelocation#234]
Currently when chunks are unloaded and reloaded the advanced filter and wireless block extender default to no filtering extraction. I have looked over your code, and if I am not mistaken, there is no NBT entry for this status, so it is not being saved when the chunks are unloaded.

It saves the filter information, what I want filtered, but it keeps defaulting to having filtering disabled entirely. Also note, your blacklist/whitelist on these two blocks is backwards as well, even WAILA states it is in whitelist mode, but is indeed in blacklist mode.

 This wouldn't be that much of an issue, but the normal filtering block extenders seem to be entirely non functional, no matter what settings I apply they seem to act as normal block extenders, but that is another issue.

**Comment by Dynious** [comment]
Closing, old report and never heard of the issue again.
