### ISSUE TITLE
ME Sorting interface: Internal Server Error/Dupe

### ISSUE THREAD

**Issue by BBoldt** [Dynious/RefinedRelocation#235]
When I connect a refined relocation network to an ME network using the ME sorting interface, it kicks me with an internal server error as well as duping the block in question.

![](http://i.imgur.com/YcIiqJm.jpg)

AE2 Rv1 Stable
Refined Relocation 1.0.6g
Forge 1231

**Comment by Dynious** [comment]
Same here, unable to confirm, closing.
