### ISSUE TITLE
Redo GUI networking system

### ISSUE THREAD

**Issue by Dynious** [Dynious/RefinedRelocation#242]
It's a mess! There are more easy and better ways than a new packet for every different button. Kind of a lot of work, this messy GUI system is present in all GUIs.

**Comment by blay09** [comment]
9b722bacafb5cb889f7a16ceeaba53fdb7a184b2 bbf8b2f0f955fde352bf611ff2a19ebbbe047781 8307b3648d5e19d3d18f555b1a0775453f4c4ed2 41df6eff6091f8dc5b05363ceda2d96be23525a2 53fb5a49f30a30c948e53cc1eb21c447bdf142cc

have all done some more work on this.

**Comment by blay09** [comment]
I consider this done now. The remaining GUI-related packets are:

SetFilterOption - too custom for generic packets since two values are sent

InsertDirection - does byte operations on sent/received values so for sanity it should stay in it's own packet so the operations stay close together
