### ISSUE TITLE
ME Sorting interface blocks AE2rv1 autocrafting

### ISSUE THREAD

**Issue by Schultz** [Dynious/RefinedRelocation#251]
Using AE2 RV1 and latest Refined Relocation 1.0.7c when i attempt to do auto craft AE2 just lists it as simulated when the ME Sorting interface is connected. The items used for crafting can be stored in a ME drive or in the Refined Relocation sorting network and it always comes up simulated. If i break the ME Sorting Interface then AE2 will do autocrafting as expected. 
![2014-12-30_14 46 11](https://cloud.githubusercontent.com/assets/1008/5583840/2f8edec2-9034-11e4-8cc6-cdb1bf208b54.png)
After ME Sorting Interface is broken.
![2014-12-30_14 46 29](https://cloud.githubusercontent.com/assets/1008/5583846/3dbc4ac0-9034-11e4-835f-0b9a60ef7896.png)

Attached is preview of test setup in test world.
![2014-12-30_14 45 51](https://cloud.githubusercontent.com/assets/1008/5583852/60e7f9ae-9034-11e4-85e0-5727a1d1aa21.png)
![2014-12-30_14 46 01](https://cloud.githubusercontent.com/assets/1008/5583853/6495f79a-9034-11e4-884d-00849d7ef9a9.png)

Pack is custom pack.

**Comment by Dynious** [comment]
After some testing both me and thatIch (AE2 dev) couldn't find any problems. Do you have enough channels left?

**Comment by Schultz** [comment]
Yes there is plenty of channels. I can see all items in both the drive and the RR side. Only the autocrafting breaks when the ME sorting interface is attached. I have bunch of other AE2 addons installed. Let me strip it down to the basics and see if something else is causing this.

**Comment by Schultz** [comment]
Just reduced the mods to the bare minimum and i still have this issue. Attached is my mod list. 

![rr test](https://cloud.githubusercontent.com/assets/1008/5599746/aef3deac-9281-11e4-90ae-366d890fd9d7.png)

**Comment by Schultz** [comment]
I figured out how to reproduce it. 

If there is a single item in the ME network (stored on one of the ME Drives) then the crafting will not work when the ME Sorting interface is attached. If everything is stored on the RR sorting system (and zero items in the ME network) then it will allow the crafting. This then causes the problem that the ME Interface will not insert items back into the ME network without some storage on the ME Network as the ME interface will not insert into the ME sorting interface. 

Screenshots attached.
![2015-01-02_13 34 12](https://cloud.githubusercontent.com/assets/1008/5599901/6a87f6c4-9284-11e4-8d94-dfa11ef12fb2.png)
![2015-01-02_13 34 20](https://cloud.githubusercontent.com/assets/1008/5599904/6e28ae40-9284-11e4-9d4b-438cd8bc4e64.png)
![2015-01-02_13 34 30](https://cloud.githubusercontent.com/assets/1008/5599906/719fd0f8-9284-11e4-8dcc-cba9d83a6fc8.png)

**Comment by Dynious** [comment]
I can still not reproduce this error. There is a ME drive in my network which stores one of the items needed to craft the pattern and a completely random item.
This works fine for me:
![image](https://cloud.githubusercontent.com/assets/3618217/5603757/095c74f8-9395-11e4-8d0d-b61c24e03a11.png)

**Comment by Schultz** [comment]
I can reliably reproduce it in my user environment (haven't ever been able to setup the dev env to work properly) Here is my world download. I will test it on a windows pc too. 

https://dl.dropboxusercontent.com/u/3689434/RR%20Test.zip

**Comment by DeForce** [comment]
Seems like the Refined Relocation Jabba ballers barrels are messing with AE

**Comment by Dynious** [comment]
YES! That's it! Trying to find out why this happens and fixing it now :D

**Comment by Dynious** [comment]
1.0.7d will have the fix for this problem! Thanks to everyone who helped to find the cause! Release should be up in a few minutes.

**Comment by Schultz** [comment]
I just tried 1.0.7d and it still has the same issue.

**Comment by cirion47** [comment]
Im having the exact same problem using RefinedRelocation-1.7.10-1.0.8b. When i connect my Sorting barrels through the ME sorting interface to my AE network my ME crafting is broken (the start crafting button is grated out). When i disconnect them everything is fine again....
