### ISSUE TITLE
visual glitch with te4 caches

### ISSUE THREAD

**Issue by LoPhatKao** [Dynious/RefinedRelocation#253]
not sure if its rr's fault, but its the most obvious victim :/

when looking at a relocator network without a cache in view, everything is fine
![2015-01-01_06 56 29](https://cloud.githubusercontent.com/assets/6551387/5592282/b67dfc10-9183-11e4-94d4-ef015e92423c.png)

when a cache is in rendered view, all sorts of weird stuff starts happening 
![2015-01-01_06 56 31](https://cloud.githubusercontent.com/assets/6551387/5592283/c009903c-9183-11e4-92d8-a89f53585880.png)

relocators go opaque, and traversing items are rendered as a square (at right edge of 2nd pic)

disabled all texturepacks to see if that helped/fixed, it didnt
installed optifine, didnt help
only thing that seems to fix it is not to use caches, but 640k item storage in 1 block? must have it lol

can provide modlist etc if needed

(ignore the noobiness of build lol.. in middle of changing storage/expanding base)

**Comment by Dynious** [comment]
I can't seem to be able to reproduce this in my development environment. Could you post the version number of CoFH Core and Thermal Expansion?

**Comment by LoPhatKao** [comment]
most recent te/tf/cofh afaik.. 
pic of my mods folder:
![mcmods](https://cloud.githubusercontent.com/assets/6551387/5592914/ae7a4ab8-91a7-11e4-9dda-4a5bcf1c6869.png)


thinking more on this issue, didnt notice happening til after i had added quarry+, remain in motion & project red (i know rim is buggy and has caused ctd a few times )

in the pictures shown earlier, the far caches by beacon beam have ic2 uranium ore, and the closer resonant caches (under chatbox) have ingots (red alloy, vanilla mc, and te types) 

beats me wtf is the root cause  .. at least its just a visual derp and not interfering with critical functions ;)

**Comment by LoPhatKao** [comment]
ok has to be something about adding mods after worldgen
tried same setup on a newly generated test world, no issues

sigh .. so its my fault lol

**Comment by Dynious** [comment]
I got this same thing to happen when holding items from JABBA, but it isn't consistent. This needs more investigation.

**Comment by LoPhatKao** [comment]
yes, this is very inconsistent..
switched from te4 caches to jabba barrels so it mostly doesnt happen anymore, but noticed it happen yesterday when a sorting alchemical chest went thru system
overlays on caches/barrels also flickered/didnt display properly when this was happening
weird

**Comment by dmillerw** [comment]
*sigh*

It's modders forgetting to cleanup after messing with GL states.
