### ISSUE TITLE
Mod-based filters and more space for user filter

### ISSUE THREAD

**Issue by Rapthera** [Dynious/RefinedRelocation#254]
Alright, I have a simple suggestion for the Sorting Chests interface, for it to expanded a bit.

* Being able to create your own mod-like filters, for example creating a filter which contains all vanilla items or editing the thaumcraft filter and adding items, eg: paper.

* Having a bit more space for writing the filters since right now after having 4,5 custom ore dictionary items makes the writing box a bit clogged up and hard to see.

I don't know if this has been suggested before, if it has I am very sorry.
cheers.

**Comment by Dynious** [comment]
The sorting & filtering interface will get a complete overhaul soon!

**Comment by blay09** [comment]
The second part of this is now implemented - you'll get a whole big multi-line box to put all your custom filters. :)

Mod-based filters is something I have planned in the back of my mind already and will get to after beautifying some more things first.
