### ISSUE TITLE
WBE should have a button to open the linked blocks interface (if there is one).

### ISSUE THREAD

**Issue by Micky2506** [Dynious/RefinedRelocation#255]
This would probably be done by simply right clicking on the linked block.

**Comment by Dynious** [comment]
I tried to add this feature when making the WBE, but some GUIs (at least vanilla ones) check the distance to a player and close the GUI when the distance is too large. I tried to work around this, but I couldn't get it working right.

**Comment by blay09** [comment]
Stumbled upon PlayerOpenContainerEvent just now, which from the looks of it might make this work and prevent the closing.
