### ISSUE TITLE
Filter Resets When Leaving Sorting Chests Interface

### ISSUE THREAD

**Issue by Nslboston** [Dynious/RefinedRelocation#256]
This strangely only seems to occur around page twelve of the creative tab filters. All filters before that point don't reset and sort properly.

**Comment by Dynious** [comment]
This should be fixed since 1.0.7a. What is the Refined Relocation version you are using?

**Comment by kegebein** [comment]
I have the same problem. Any filter checked after the 129th option is unchecked after leaving the interface dialog.
I am using Refined Relocation version 1.0.7d (included in the Tolkiencraft II v2.3.16 modpack).

**Comment by Dynious** [comment]
Damn, I have no idea why this happens :(

**Comment by kegebein** [comment]
Any way I can help you to find the culprit?

**Comment by Dynious** [comment]
No GitHub, don't auto close D:
