### ISSUE TITLE
Sorting Barrel Dupe Bug

### ISSUE THREAD

**Issue by Serifina** [Dynious/RefinedRelocation#257]
There is a very nasty dupe bug with the Sorting Barrels.

To reproduce: Set a JABBA barrel down, give it some space upgrades. Put some stuff into it (cobble, a TC staff, whatever). Apply a sorting upgrade to it. Instantly, exact copies of everything applied to the barrel (upgrades, stored items) will pop out and onto the ground. Everything also stays within the barrel, giving you exact copies of every item.

Tested with the latest version, using this pack: http://www.technicpack.net/modpack/eranthepack.542215

**Comment by Dynious** [comment]
This seems to be an issue since JABBA 1.2.0. Thanks for reporting this! I will see if I can fix this on my side :)
