### ISSUE TITLE
Refined Relocation interface and AE channels

### ISSUE THREAD

**Issue by DeForce** [Dynious/RefinedRelocation#258]
Good Day,

At the moment you are able to connect all refined relocation system to AE with no effort only for 1 channel. Is it possible that in future I'm able to change the amount of channels needed for the Refined Relocation Interface to connect? Maybe make it scaling with the amount of chests/barrels in the RR system? 1 channel for 20+ barrels and chests seems kinda op :(

**Comment by Jasems** [comment]
I tried to recreate this type of setup, but it escapes me I think.  I linked a storage bus w/a wireless block extender, but anything next to the wireless block extender doesn't get seen in the AE2 network by the storage bus doing that.

**Comment by Dynious** [comment]
Seems like this currently is impossible because it's not supported in Applied Energistics. This isn't that OP when you compare it to a ME drive which might even be able to store more than 20+ barrels with one channel.

**Comment by Jasems** [comment]
Yeah, the barrels seems to work great. I think I originally misunderstood what he was doing.  I couldn't get it to work with things like deep storage units (even with a sorting interface) so that makes it less OP at least. :)
