### ISSUE TITLE
filtering hopper only fills 4 slots

### ISSUE THREAD

**Issue by LoPhatKao** [Dynious/RefinedRelocation#259]
found this one by accident ;D

set to only accept gems, fed by relocator
sent a bunch at it, when relocator going into it was stuffed, opened hopper .. only 4 stacks
i can manually place a stack in last slot, but not automagically via relocator :(

![2015-01-06_19 33 52](https://cloud.githubusercontent.com/assets/6551387/5639873/024eaf26-95db-11e4-843a-fd7809b5ec62.png)
![2015-01-06_19 33 57](https://cloud.githubusercontent.com/assets/6551387/5639878/119108b2-95db-11e4-986d-9e2396de0541.png)

edit: using it as a regular hopper with filter is fine, it just seems to be when fed by relocator

**Comment by Dynious** [comment]
Thanks for reporting! Woops, will fix now :)
