### ISSUE TITLE
ProjectE Alchemical Chest support

### ISSUE THREAD

**Issue by Sailren** [Dynious/RefinedRelocation#260]
hello dynious

would it be possible to add sorting chests support for ProjectE alchemical chests? i really like these chests and others maybe too.

greetz

Sailren

**Comment by LoPhatKao** [comment]
have you tried this?
https://www.youtube.com/watch?v=gf7iNMy0-1M#t=834


probly be better for your purposes

**Comment by blay09** [comment]
If support for ProjectE alchemical chests is still desired, please bring this issue over to their tracker and ask them nicely to add Refined Relocation sorting versions of their storage blocks using RR's API.

Alternatively, use the Sorting Interface and wait for #306 to make the Sorting Interface work for input items too.

**Comment by Sailren** [comment]
well projecte is overpowered in my opinion, what about EE3? do i remember correctly that this mod works with RR?

**Comment by blay09** [comment]
We do provide Sorting Alchemical Chests from EE3 at the moment, yes.
