### ISSUE TITLE
Buildcraft 6.3.1 incompatibility

### ISSUE THREAD

**Issue by soratobukuroneko** [Dynious/RefinedRelocation#265]
compatibility broken BC 6.3.1, smp server or single player client crash when loading my world

logs : https://gist.github.com/soratobukuroneko/5eb1e63841144fc9fe96

**Comment by LoPhatKao** [comment]
indeed :(

http://pastebin.com/pwheX3D4

**Comment by Dynious** [comment]
Buildcraft is changing a lot of things in their API, which breaks compatibility with other mods :(
I currently don't have the time to make the required changes and push a release. In about a week I should have a week off and plenty of time :D

**Comment by LoPhatKao** [comment]
if i had any idea how to do java, id fork and try to fix
unfortunately all my experience is in c ;/
guess ill stick to bc 6.26 for now.. as RR is my main item pipe system

**Comment by soratobukuroneko** [comment]
Is the commit 2307810a228263 supposed to be 100% compatible with BC 6.3? I quickly tried to build following the README instruction, works with latest 6.2 but not latest 6.3

**Comment by Dynious** [comment]
@soratobukuroneko Yes, it should. Could you post the log?

**Comment by soratobukuroneko** [comment]
of course
https://gist.githubusercontent.com/soratobukuroneko/d3180394f0e702f42e14/raw/fml-client-latest.log

**Comment by Dynious** [comment]
Fixed in 1.0.7e!
