### ISSUE TITLE
[1.0.7d] Crash with Buildcraft

### ISSUE THREAD

**Issue by JasonMcRay** [Dynious/RefinedRelocation#270]
When I try to connect Buildcraft Wooden Transport Pipe to Relocator pipe, the crash will occur and the world will become not loadable afterwards.

CrashLog: http://pastebin.com/ngVynimw

RR: 1.0.7d
Buildcraft: 6.3.3 (tested also with latest 6.3.6, same crash)
Forge: 10.13.2.1232

**Comment by Dynious** [comment]
Fixed in 1.0.7e!

**Comment by JasonMcRay** [comment]
Wow. That was fast. Thank you very much @Dynious you are awesome

**Comment by Dynious** [comment]
Thanks :D
