### ISSUE TITLE
Module Extraction disappears

### ISSUE THREAD

**Issue by toticorrea** [Dynious/RefinedRelocation#273]
I have Minecraft 1.7.10. From time to time, the module extraction I put disappears. I have not noticed so far if it does exactly when I do a specific task. At the beggining I though that was every time I add or remove a sorting chest from my set up, but then today it was already missing when I opened the map.

**Comment by toticorrea** [comment]
I also noticed that the module extraction "puls out" from the relocator tube and stays "floating" like any object you discard in Minecraft. So if you do not notice this in a propper time, the module extraction, like any other object discarded, disappears after a while. But I do not know what causes the module extraction to be separated from the relocator. Any ideas?

**Comment by Dynious** [comment]
It probably thinks it has lost connection the the block it's connected to and drops. Not quite sure what causes it to think it lost connection.

**Comment by toticorrea** [comment]
I will try to run a couple of tests, like break a chest, putting another, replace a relocator section, etc to see what happens, if I can find some consistence, but I am prettty sure it also happened while I did nothing to my sorting system, just playing in another place in the map.
By the way, I have like 30 sorting chests in my basement conected with another one  at the first floor. Also another chest connected with a furnace and this one again connected with the fisrt chest to sort the items the furnace pulls out. A few of them upgraded with the Iron-Chest Mod. Also I have 50 mods running, including yours.

**Comment by toticorrea** [comment]
Meanwhle, I had to improvise, taking out the module extraction and keeping it in the chest when I am not using the sorting system, so i do not keep loosing them...  :(

**Comment by Dynious** [comment]
Could you post a screenshot of your setup? Preferably with the chunk boundary lines enabled.

**Comment by toticorrea** [comment]
ok.

**Comment by toticorrea** [comment]
![image](https://cloud.githubusercontent.com/assets/11169671/6539902/890b491a-c462-11e4-9a78-a3ab7cfe30be.png)

**Comment by toticorrea** [comment]
![image](https://cloud.githubusercontent.com/assets/11169671/6539910/b23d27c2-c462-11e4-8fd7-bd870e82de5a.png)

**Comment by toticorrea** [comment]
![image](https://cloud.githubusercontent.com/assets/11169671/6539913/ca265304-c462-11e4-82b9-f02f9c307232.png)

**Comment by toticorrea** [comment]
is this what you asked for?

**Comment by toticorrea** [comment]
Just happened again! It was when a pause the game for a long time (more than 30 minutes-1 hora, when I try to come back or the game stops working or starts with a lot of lag. I do not know what couses this. Anyway, also 3 of my 5 extraction modules where out of their places, 1 missing and 2 floating near its location. And I would have to make sure about this, but I think its the same 3 modules every time, and not the others two. Also I noticed that after playing a while my game starts to lag a lot. But at the beggining is just perfect

**Comment by Dynious** [comment]
I don't see an extraction module on those images, but I could be missing it. 

What I think is happening is that the blocks where the relocators with extraction modules are attached to are in a different chunk than the relocator. This means the chunk of the block could unload while the chunk of the relocator doesn't unload. If this happens the relocator might think it's no longer connected to a block and disconnect which will drop the extraction module as an item.

This should not happen, as checking the block will load the chunk, but some mod (or a bug in Minecraft) might break this. I have no idea how to check this and how to fix this :S I can imagine that this is extremely frustrating for users :(

**Comment by toticorrea** [comment]
What you can see there is the sorting chest system in the basement. I´ll put nknow where the modules are

**Comment by toticorrea** [comment]
![image](https://cloud.githubusercontent.com/assets/11169671/6543306/cbbea156-c4f5-11e4-9c2c-856d87cc0c96.png)

**Comment by toticorrea** [comment]
![image](https://cloud.githubusercontent.com/assets/11169671/6543308/e58bb4b6-c4f5-11e4-83f4-4ac3f0a812af.png)

**Comment by toticorrea** [comment]
these are the 2 chests the extraction relocators. The left one goes with the pipes directly to the basement or the kitchen if there is food traveling. The one at the right goes to the furnace. These are the two that I always keep losing

**Comment by toticorrea** [comment]
![image](https://cloud.githubusercontent.com/assets/11169671/6543333/8fd2ef2a-c4f6-11e4-913c-a9a5854582dc.png)

**Comment by toticorrea** [comment]
This wireless block extender with the extraction module is attached to the furnace. This one I didn´t loose.

**Comment by toticorrea** [comment]
![image](https://cloud.githubusercontent.com/assets/11169671/6543347/f4fb4b68-c4f6-11e4-9d64-4838f6b6ae54.png)

**Comment by toticorrea** [comment]
And here you can see the block extender with the extraction module for the chest with coal witch feed the furnace. This one I keep losing too. At the top you can see the wireless block from the bottom view.

**Comment by toticorrea** [comment]
What about this idea (remeber I am not a programmer, so I might saying non sences here). What about an advance block extender with the capability of extraction on it? So you do not need to use the module extraction?

**Comment by Dynious** [comment]
Thanks for helping me with this! I hope I can figure out the issue now.

**Comment by Dynious** [comment]
I found out why this happens! When the world loads all blocks load their settings and initialize. When the Block Extenders haven't yet initialized they will not yet act like they can transport anything because they haven't loaded their connected block yet. So when the Relocators load before the Block Extenders the Relocators will think the Block Extender is not a valid inventory and will disconnect.

Now I just need to think about how to fix this properly.

**Comment by Dynious** [comment]
Fixed it! Many thanks for your help on this!

**Comment by toticorrea** [comment]
It will be on the next upgrade?
