### ISSUE TITLE
Power-Transfer not working

### ISSUE THREAD

**Issue by Nezraddin** [Dynious/RefinedRelocation#275]
Version 1.0.7f

It seems that neither the buffer nor the block-extender seems to accept any kind of RF power. I tried with connecting galacticcraft-wires, energy transfernode+energy pipe (extra utilities) and an energy-cell (thermal expansion). The buffer seems to "see" what is connected, but cannot put the energy through at all.
(the huge buffer stays at 0 as well... actually not sure if the buffer is a bug in waila, it shows over 21 million rf or so as buffer)

**Comment by Dynious** [comment]
Could you post the mods list? I have a hard time finding out what causes this as it seems like there's nothing wrong when I try.

**Comment by peptide** [comment]
It seems to be to do with the item/mod that is receiving power. If I place an energy cell, then any power cable then extender and then item to receive power. If the item is a machine from thermal expansion or the energy accepter from AE2 the cable does not connect to the extender and no power is transferred. If i place an TE energy cell, or a gendstry apiraiy then the connects and transfers.

**Comment by squeek502** [comment]
Post a screenshot of a setup that doesn't work.

**Comment by Dynious** [comment]
I think I figured it out. TE split up the EnergyHandler into an EnergyReceiver and an EnergyOutputter, but kept the EnergyHandler which extends both EnergyReceiver and EnergyOutputter, which means that there will be no crash, but when something only implements EnergyReceiver Refined Relocation will not send power. Should be an easy fix!
