### ISSUE TITLE
Itemduct (Thermal Dynamics) sees relocator (tube) as a single slot inventory. (Maybe?)

### ISSUE THREAD

**Issue by DeForce** [Dynious/RefinedRelocation#279]
Good day,

I have setup 4 powered furnaces and connected them with itemducts, when relocator system has item  in it, itemducts doesn't extract items from furnaces.

Setup: (4 powered furnaces, 3 of them have copper dust in them and the last one have gold)
http://i.imgur.com/OmNQ5dp.png

As you can see, copper is traversing the relocator:
http://i.imgur.com/xcIVwwa.png

and copper is extracting fine:
http://i.imgur.com/BfBzTza.png

But gold doesn't:
http://i.imgur.com/2oLWsnC.png

Best Regards,
DeForce

**Comment by Dynious** [comment]
Yea, it kinda is a one slot inventory per Relocator side. You might want to disable the controlled sending thing they have (or enable over-sending, not sure what they call it). I cannot really change it, because it might break other things.

**Comment by DeForce** [comment]
Yeah, started to use that setting.
