### ISSUE TITLE
Refined Relocation crashed because of the new AE beta

### ISSUE THREAD

**Issue by DeForce** [Dynious/RefinedRelocation#280]
Good Day,

From AE 20 beta i'm getting crash on startup.
19 beta also gives crash but with different reason.
18 beta works fine.

http://pastebin.com/tpFs4VqE

Best Regards,
DeForce

**Comment by Dynious** [comment]
Applied Energistics seems to have broken their API, have you already reported it to them?

**Comment by DeForce** [comment]
There is comment on new version:
For developer: Deprecates the old usage of the AEItemDefinitions via the direct method access of * blocks() * parts() * items() * materials() and thus use the new re-direct via definitions(). All definitions are now initialized, no matter what. But SubItems, Items and Blocks are not registered, if by chance are disabled. - thatsIch

Soo, I wanted to confirm if I should report it to them rather than to you.

**Comment by Dynious** [comment]
Talked with the AE guys about this. Seems to be some kind of error on their side and they are making changes to no longer make it seem like other mods are causing it. Thanks for reporting!
