### ISSUE TITLE
Server crashes with new version 1.0.8

### ISSUE THREAD

**Issue by Tomson124** [Dynious/RefinedRelocation#281]
Server crashed with the new version of RefinedRelocation:

http://pastebin.com/skLyszyB

**Comment by Dynious** [comment]
Weird, this crash report makes no sense to me. I'll try to reproduce it and fix it ASAP :)

**Comment by Tomson124** [comment]
Thanks. I hope it is not a conflict with other mods... But it occurs only on my server, the client is running fine with version 1.0.8.

**Comment by Dynious** [comment]
I'm unable to reproduce this :( I made a new server instance with the latest Forge and added Refined Relocation to it. Everything runs fine. Are you using the same file for the client and server? Maybe the file on the server got damaged when downloading.

**Comment by Tomson124** [comment]
Thanks. Yeah, it was an Upload issue.... 
Sry for stealing your time :/
