### ISSUE TITLE
Improve user-friendlyness of UIs

### ISSUE THREAD

**Issue by blay09** [Dynious/RefinedRelocation#286]
- [x] Edit Filter button for Sorting chests, not just sneak right-click
- [x] Redstone Toggle UI button even for the simple one, not just sneak right-click
- [x] Clarify Max Stack Size in tooltip - it's per stack, not a total of the inventory!
- [ ] Arrange Block Extender sides in a common unwrapped-cube alignment
- [x] Add orientation to block extender side selection tootlip and clarify what it does (e.g. "Access from NORTH" as tooltip)
- [x] Advanced Buffer needs clarification (what do the numbers mean?)
- [x] Power Limiter GUI
- [x] Sorting Importer GUI
- [x] Insert/Extract side: name it "top" and "bottom" instead of "up" and "down"
- [x] Add more info to all the tooltips in general - maybe do the "- Press SHIFT -" as second line thing and have more info appear in tooltip when holding shift

**Comment by squeek502** [comment]
All good ideas. Removing the need for sneak+right click to access filter settings would be a huge boost in terms of intuitiveness.

**Comment by Dynious** [comment]
It would, but this is gonna be very hard, we would need to inject a button in a GUI without access to the code of the GUI. This might be possible because of the way MC GUIs work, but expect lots of breakage.

**Comment by blay09** [comment]
This is what the GuiEvent.InitGui and GuiEvent.ActionPerformed forge events are for, so injecting the button shouldn't be hard at all (see how it works fine for Inventory Tweaks). We'll just have to make sure it's positioned correctly.

**Comment by squeek502** [comment]
Good work @blay09. :+1:
