### ISSUE TITLE
Problem with newer versions of Forge and FMP

### ISSUE THREAD

**Issue by Haggle1996** [Dynious/RefinedRelocation#287]
https://gist.github.com/Haggle1996/b77066a71f727edd2766

Encountering a problem when adding FMP to an existing pack with RR in it. Forge barfs on loading the FMP version of the relocator in an existing save.

This is extremely easy to replicate. Create a new vanilla install with recent Forge and RR. Create a new world. Close Minecraft and add Forge Multipart. Now try to reload the world. You'll recieve the following error message in the log:

"There is a high probability that a mod has broken the
ID map and there is
NOTHING FML or Forge can do to recover this save."

If its not possible to fix this problem, could a config option be added instead that makes RR ignore the presence of FMP?

**Comment by blay09** [comment]
@Dynious Possible solution: register the relocator even if FMP is loaded but instead of adding the recipe for that one, add a recipe that turns non-fmp relocators into fmp-relocators?

**Comment by Dynious** [comment]
Yea, there's not a lot we can do at this moment. It was a bad decision to do this the way I did, I didn't really think of people adding and removing FMP.

**Comment by Haggle1996** [comment]
I built a one-off version of RR 1.0.8b with IS_FMP_LOADED set to false instead of the lookup. This seems to solve the problem without breaking maps created with my pack. This version is only distributed inside my AT Launcher modpack. I believe this is in accordance with your LPGL license, but if there are any problems, please let me know and I'll come up with something else.

**Comment by Dynious** [comment]
That will work and is absolutely fine :) I could make this a config option, so you could force-disable FMP integration, if you would like that!

**Comment by Haggle1996** [comment]
Making a config option is preferable so I don't have to make a one-off every time RR updates -- but regardless, thanks for making an awesome mod and helping with the issue. :)

**Comment by Dynious** [comment]
6f25a791bd5a97ebcdc293da20fdbd886f157b2a adds the config option!

**Comment by Haggle1996** [comment]
Looks perfect. Thanks!
