### ISSUE TITLE
Cannot pickup Wooden Sorting Chest with Dolly

### ISSUE THREAD

**Issue by Haggle1996** [Dynious/RefinedRelocation#288]
Cf Haggle1996/RevolutionPack#12 Users cannot pick up the wooden sorting chest with a JABBA dolly (either version). They can pick up any other chest from RR.

**Comment by blay09** [comment]
This requires JABBA to add the sorting chest to it's supported inventories.
I've opened up an [issue on their issue tracker](https://bitbucket.org/ProfMobius/jabba/issue/132/cannot-pickup-sorting-chest-from-refined).

**Comment by Haggle1996** [comment]
Awesome, Thank you. I'll poke ProfMobius until its done.

**Comment by blay09** [comment]
Grew tired of waiting. Fixed in next version, but might stop working again if JABBA changes their internal implementation (probably not going to happen). Chests won't rotate accordingly though, that's something that can truly only be done within JABBA (or by JABBA providing a proper API).
