### ISSUE TITLE
WAILA data is incorrect until GUI has been opened at least once

### ISSUE THREAD

**Issue by blay09** [Dynious/RefinedRelocation#293]
The fix for this is to send the filter and other relevant data in the TileEntity data packet, so the client receives it even if he hasn't opened the GUI at least once yet.

The problem is that all the sorting chests from other mods have their own description packet so we can't just do it like that there...

**Comment by squeek502** [comment]
If the data is in the NBT tag, you can use the Waila API to retrieve it as necessary.

It's already done for certain RR tiles:
https://github.com/Dynious/RefinedRelocation/blob/master/src/main/java/com/dynious/refinedrelocation/mods/WailaProvider.java#L28-L32

**Comment by squeek502** [comment]
If you want Waila to only sync certain NBT keys:

For Waila >= 1.5.6: http://www.mobiusstrip.eu/2014/12/14/waila-1-5-6-for-mc-1-7-10/
For Waila < 1.5.6: https://github.com/squeek502/VeganOption/blob/master/java/squeek/veganoption/integration/waila/WailaRegistrar.java#L16-L24

**Comment by Dynious** [comment]
I'll try to find out why this isn't working as it should be. Looking at the code it seems like things should work, but something with sending or reading the server NBT on the client doesn't seem to work.
