### ISSUE TITLE
[Suggestion] Remove Sorting Iron/Alchemical Chests in Minecraft 1.8

### ISSUE THREAD

**Issue by blay09** [Dynious/RefinedRelocation#294]
I highly advise against adding any more of these Sorting XYZ from other mods and encourage people to use Sorting Interfaces instead or provide a good API that other modders can use to add support for their mods themselves.

It's a nice thing to have, but due to the way it has to be done (i.e. by accessing internal code from other mods), it's causing more problems than benefits and makes keeping things stable and up to date harder (see #293 for an issue with WAILA data, for example).

Obviously they can't just be removed like that as it would result in people losing their chests, but it could be done in between a Minecraft version update where everyone resets their world anyways.

**Comment by Dynious** [comment]
Sorting Interfaces are not a good alternative to having the implementation (it's only receiving items). There is a good API and it's being used (by Enhanced Inventories, Storage Drawers and soon Compact Storage). Refined Relocations popularity is not high enough at this point to not do some of the implementations on our side. JABBA and Iron Chest are essential, but I don't see them adding support anytime soon.

Obviously I would prefer their implementation of the API too.

**Comment by blay09** [comment]
Should rethink this once #306 is done. But even then, I guess an implementation for JABBA and Iron Chests is "okay", since those seem to be the most popular storage mods.

However, I'd rather not do any further things like adding support for e.g. Project E chests. People can go bug Project E for that instead.
