### ISSUE TITLE
Weird Relocator Module GUI issues

### ISSUE THREAD

**Issue by whitestarx0312** [Dynious/RefinedRelocation#298]
When using a relocator pipe with modules, the module GUI almost always messes up and cannot be interacted with. I have found no work-around for this, and it happens with all modules on a relocator pipe. 

RR: RefinedRelocation-1.7.10-1.0.8b
Forge: forge-10.13.3.1401
AE2: appliedenergistics2-rv2-stable-1
Agrarian Skies 2: 1.0.42

Before: http://imgur.com/CJDumZf
GUI: http://imgur.com/t0iJ5Pr
*I am using Optifine and Fastcraft.

**Comment by Dynious** [comment]
Thanks for reporting, I will take a look at this!

**Comment by whitestarx0312** [comment]
Sweet :)

**Comment by Dynious** [comment]
I'm unable to reproduce this. Could you give me a little bit more info? What modules have you added (only the FIlter one?)? Are you playing on a server or single player? Is there anything in the logs? What happens if you stop the world and restart it? Anything else that might be useful. Thanks :)

**Comment by whitestarx0312** [comment]
Alright:
1) I am playing Agrarian Skies 2 on the boni-normal level (nothing special)
2) I am on single player.
3) I added the multi-module module, sneaky extraction module, and filter module.
4) It is connected to an Applied Energistics 2 Inscriber.
5) The only thing in the log that mentions RR is this:
13:35:00] [Client thread/INFO] [inventorytweaks/]: com.dynious.refinedrelocation.client.gui.GuiHome
[13:35:00] [Client thread/INFO] [inventorytweaks/]: com.dynious.refinedrelocation.container.ContainerMultiModule

*Relogging does not fix the issue.

**Comment by Dynious** [comment]
Finally able to reproduce! Only happens when Inventory Tweaks is loaded. More investigation needed.
