### ISSUE TITLE
Issue with Router Reborn

### ISSUE THREAD

**Issue by whitestarx0312** [Dynious/RefinedRelocation#299]
Please see: https://bitbucket.org/zyberwax/main/issue/13/router-reborn-with-refined-relocation

**Comment by Dynious** [comment]
Thanks for reporting this! And you running Forge Multipart? If yes, I think the issue they are dealing with applies to all FMP blocks they are checking (IInventory implementers?) including Relocators. If no, I have no idea why this happens, but I'll try to find out.

I'm unable to make a Bitbucket account at this moment, but will do so soon to directly communicate with the devs if needed.

**Comment by whitestarx0312** [comment]
Yes I am. Alright sweet, thanks for the quick reply!

**Comment by whitestarx0312** [comment]
The issue seems to be on the Router Reborn side per the bitbucket issue. Thanks for looking into it anyway! :)
