### ISSUE TITLE
Sorting Chests aren't working with new Forge.

### ISSUE THREAD

**Issue by spitfire1081** [Dynious/RefinedRelocation#302]
I run several experimentations with the sorting chests in my server and it looks like they are not working with the new forge.

It was running OK before we upgraded forge in our server.

**Comment by Dynious** [comment]
Oh noes. I will look into this. Thanks for reporting!

**Comment by spitfire1081** [comment]
I run some tests yesterday due to this.

Using forge 1370, itemducts and ender io itemducts worked perfectly with refined relocation white list.

Now, sorting chests just work if they are directly conected to the inventories, itemducts won´t respect the whitelist of the chest.

Is there a way to fix this?

**Comment by Dynious** [comment]
Did you maybe alsod update any CoFH mod? CoFH Lib/Core maybe? If CoFH changed insertion and EIO used their insertion method they might both break.

**Comment by spitfire1081** [comment]
I am using the latest versions of both CoFH and Ender IO.
I didn´t see any changes in the insertion method but this ignoring the sorting white list.
Most modpacks use IC2, CoFH Mods and Ender IO as core mods.
If something changed, maybe it would be a good idea to update Refined Relocation, don´t you think?

**Comment by Dynious** [comment]
I can't fix this if I don't know what the problem is. If CoFH has a change that breaks insertion, I'll need to report it there. Could you give me a list of CoFH mods and Forge versions when it did work and the current ones where it doesn't work? This will make finding the issue a lot more easy.

**Comment by spitfire1081** [comment]
Of course. I will put the CoFH versions, the insertion of ender IO is the same. If you find the problem for one, you fix both.
Oh, Extra Utilities pipes and buildcraft pipes, same issue... they won´t respect the sorting white list.

When it worked:
Forge 1370
CoFHCore-[1.7.10]3.0.2-262.jar
ThermalFoundation-[1.7.10]1.0.0-81.jar
ThermalExpansion-[1.7.10]4.0.1-182.jar
ThermalDynamics-[1.7.10]1.0.0-122.jar

When the itemducts don´t respect the sorting chests white list:
Forge 1408
CoFHCore-[1.7.10]3.0.2-262.jar
ThermalFoundation-[1.7.10]1.0.0-81.jar
ThermalExpansion-[1.7.10]4.0.1-182.jar
ThermalDynamics-[1.7.10]1.0.0-122.jar

Only difference is forge version... i checked the code myself and i didn´t understand it too.
Maybe if you check this in game you can comprehend better, since you wrote the code.
Checking it with a quick overview, i didn´t find any issues and no explanation why this is happening...

**Comment by Dynious** [comment]
Tried a few setups and it seems to work as intended with the same Forge version as you used. Could you describe (or screenshot) the setup that isn't working?

**Comment by blay09** [comment]
Was able to reproduce on a super-simple setup using Forge 10.13.3.1428 with EnderIO (latest CF version) conduits.

[Sorting Chest] - - [Chest]

Sorting Chest is set as "All Ingots" whitelist. Extracting from another chest with Stone and Ingots will move both to the chest, even though the Stone should be rejected.

I also tested it with a furnace, which only allows burnable items in it's bottom slot; the EnderIO conduit worked fine there and only extracted coal from the sender chest, not the Stone/Ingots - so it's not an issue on their side.

**Comment by Dynious** [comment]
The setup you described there isn't a bug, it's normal behavior. Sorting Chests only sort between each other, they will still allow items not in their whitelist to go in. This has always been the case and cannot be changed or we will break players setups.

**Comment by blay09** [comment]
Oh! Alright. I guess that makes sense, otherwise there wouldn't be a way to have a single input chest that gets filled by a pipe (other than messing with priorities).

If I connect another chest that can hold the Stone, everything works fine.

**Comment by blay09** [comment]
Assuming this is no longer relevant since no one else is having issues.
