### ISSUE TITLE
Dupe with relocators and compact chests.

### ISSUE THREAD

**Issue by NolanSyKinsley** [Dynious/RefinedRelocation#304]
I placed a max size chest from compact chests on top of a sorting interface, then placed 2 relocators going from the chest back down to the interface and placed an extractor upgrade on the chest. The relocators then fed everything one by one in the chest into the sorting interface and when they reappeared in the chest it had doubled every item.

I restarted to make sure and it  still persists and the dupe items were not ghosts.

**Comment by blay09** [comment]
Can confirm this works, was able to reproduce with both the Compact Chest as well as a simple Vanilla chest.

@Dynious halp
