### ISSUE TITLE
ME Sorting interface does not show items across interface.

### ISSUE THREAD

**Issue by NolanSyKinsley** [Dynious/RefinedRelocation#318]
Simply put, any items on the network from an ME sorting interface are not visible to another network looking through a storage bus at an interface on the subnetwork with the sorting system on it. I have a feeling this may be linked to #316

**Comment by amezick** [comment]
I am using the Agrarian skie 2 pack and having the same issue.  I have a wall of sorting barrels with one sorting chest.  I have a wall of compacting drawers with two sorting chests.  I can have 1 ME sorting interface connected to one of the walls.  As soon as I connect both walls I can no longer craft.

**Comment by blay09** [comment]
The ME Sorting Interface is likely going to be removed in the future. It's causing quite a few issues and was never balanced in the first place (it basically replaces the need for several storage buses by one block).
