### ISSUE TITLE
Get rid of the update notification when joining the game

### ISSUE THREAD

**Issue by blay09** [Dynious/RefinedRelocation#324]
Mods that do this are literally Satan.

It just causes extreme chat spam, even more so in Modpacks because every mod thinks it's so important it needs to put five lines of text to notify users about a new version.

I've never heard of a single person who finds these notifications useful or likes them.
There's just hate. All hate.

**Comment by blay09** [comment]
@Dynious Just making sure you're alright with this?

**Comment by Dynious** [comment]
When Version Checker is installed it doesn't do this :P 
But AFAIK it should disable the message after showing it once. I might have derped and broke that.

**Comment by blay09** [comment]
It could be reduced to one line by adding a clickable link and removing the changelog from there. That'd be more bearable than it is now at least.
