### ISSUE TITLE
Rename Sorting Importer

### ISSUE THREAD

**Issue by blay09** [Dynious/RefinedRelocation#327]
I'm not sure what it could be renamed too, but I feel like it definitely needs a different name.

I always thought it had to do with Applied Energistics...but even if you're sane then it still feels like the block imports it from somewhere, rather than being a standalone block you can right click with stuff.

**Comment by Dynious** [comment]
I... don't know a better name.

**Comment by blay09** [comment]
Sorting Import Pane? As long as it's not Import*er* it doesn't sound like it works by itself. Pane sounds like something the user interacts with.
