### ISSUE TITLE
Decide on ONE material for sorting chests / upgrade

### ISSUE THREAD

**Issue by blay09** [Dynious/RefinedRelocation#328]
The "Requires two ingots of chest type" thing of the upgrade is not very intuitive.
I see why it's required (so to not be cheaper than the other recipe), but I'd rather just have one material that's used for all sorting chests and the upgrade rather than this.

**Comment by Dynious** [comment]
This 'ask for items' way was quite recently added and I think this is the best way we can do this. This way players who do not have Iron Chests or other supported chest mods installed can still use Sorting Chests without them costing waaay to much.

**Comment by blay09** [comment]
Just have it always be wood? They did already spend iron on the Iron Chest itself, after all.

**Comment by Dynious** [comment]
But you can then sort more slots for the same price, doesn't seem fair.

**Comment by blay09** [comment]
Can already do that with a Sorting Interface. You need to balance between fairness and intuitiveness.
