### ISSUE TITLE
1.1.0

### ISSUE THREAD

**Issue by Dynious** [Dynious/RefinedRelocation#329]
We should make a list of things we want to be fixed/added before we release 1.1.0. There has been lots of additions and changes lately and I think working towards a release soon wouldn't be a bad idea.

**Comment by Dynious** [comment]
- [ ] Finish up Same Item filter
- [ ] Add metadata & NBT check options in crafting module
- [ ] (optional?) Finish and merge Relocator metal branch

**Comment by blay09** [comment]
This is what the Milestones in GitHub are for \o/

**Comment by Dynious** [comment]
I know, but not all our additions and changes have open Github issues.

**Comment by blay09** [comment]
In that case they should get an open GitHub issue.

**Comment by Dynious** [comment]
The two things left to do are no longer in-scope for 1.1.0 and can cause issues. Might open separate issues for those later.
