### ISSUE TITLE
Sorting Interface dupe bug.

### ISSUE THREAD

**Issue by go371211** [Dynious/RefinedRelocation#331]
If you pump item into a sorting interface attached to a chest(inventory) and set the priority to low, item will show up in both the chest(inventory) that attaches to a sorting interface and the other chests(inventory) that has higher priorities.

**Comment by blay09** [comment]
I can't seem to reproduce this, could you go more indepth with your setup (what are you using to move the items, what chests are you using, what kind of filters do you have set, etc)? A screenshot of your setup would be ideal, so I could rebuild it.

**Comment by go371211** [comment]
![2015-06-27_10 12 39](https://cloud.githubusercontent.com/assets/11721151/8390076/743edaaa-1cb5-11e5-931b-122415658ff3.png)
Two sorting interfaces attached to two barrels(can be any types of inventory space). Both sorting interfaces set to blank black list. Left one has normal priority. Right one has normal-high priority. Left barrel hooked up to a relocator with a extraction module(can be any types of transferring method). And...

![2015-06-27_10 12 47](https://cloud.githubusercontent.com/assets/11721151/8390101/687f6cec-1cb6-11e5-86a2-a967b1bdd347.png)
![2015-06-27_10 12 53](https://cloud.githubusercontent.com/assets/11721151/8390103/7363f844-1cb6-11e5-8c4f-66fb2291df43.png)
![2015-06-27_10 13 23](https://cloud.githubusercontent.com/assets/11721151/8390106/7663bb6a-1cb6-11e5-9d3f-c08fd7cf47e8.png)

**Comment by blay09** [comment]
Ah, this looks like #304 which has been fixed for the upcoming new release.

Thanks for the elaborate screeshots though!
