### ISSUE TITLE
Duplication bug with Equivalent Exchange 3

### ISSUE THREAD

**Issue by LemADEC** [Dynious/RefinedRelocation#336]
Using only RefinedRelocation 1.0.8b and Equivalent Exchange 3 0.3.507, when you place two Sorting alchemical Chests next to each other, and set one to All ingots and leave the second one alone, you can shift click ingots into it forever. The Duped ingots will be in the chest set to All ingots, you can dupe with most of the Sorting Options.

**Comment by blay09** [comment]
See #330, this will be "fixed" in the next version by removing the support for Sorting Alchemical Chests.
