### ISSUE TITLE
Void barrels holding phantom stack, revealing it through ME sorting interface

### ISSUE THREAD

**Issue by Shurhaian** [Dynious/RefinedRelocation#339]
I have a wall of sorting barrels receiving the output of my farm. These have (for the most part and for purposes of example) a single storage upgrade each, bringing them to a capacity of 128 stacks - for the typical items like I'm storing here (no eggs in this bunch), that's 8192 items. They also have void upgrades so that extra items don't clog up the system. An ME sorting interface is contiguous with these barrels and connected to my AE system.

AE reports having access to 8256 artichokes (and same for other crops in that section). If I disconnect the sorting interface I don't have any, and the sorting interface is the only device on that cable run so there's nowhere else they might be being stored. I have checked the sorting chest which serves as input for the barrels, and it doesn't contain the extra stack (nor anything else). On the barrels themselves and in WAILA, the barrels report 8192 items. However, they seem to have a "hidden" stack above and beyond the expected total; I can pull a stack from those barrels (by hand from the barrel itself) and they'll still report full, but the value in AE drops to the expected max of 8192 and fills up with the extra stack from there.

This is not happening with non-sorting JABBA barrels; those immediately drop count by a full stack when a stack is removed.

**Comment by blay09** [comment]
Just tested this in my dev environment and can no longer reproduce it.

I assume Dynious fixed it in 95cdaa45d91c8ff0fc8fbfd98d5f2ddae56a9274.
