### ISSUE TITLE
Unable to open config interface on Mac OS X, in the Crack Pack

### ISSUE THREAD

**Issue by joakimar** [Dynious/RefinedRelocation#341]
I'm guessing due to right-click difference (two-finger on trackpad, or ctrl-click)

I've tried all combinations like shift-two-finger, shift-ctrl-click.

**Comment by joakimar** [comment]
… and just now I realized I need to do this with an open hand. Doh.

**Comment by blay09** [comment]
There'll be a button to open the filter settings in the upcoming version, so that should become easier to deal with then too. :)
