### ISSUE TITLE
Optional weighted value on each whitelisted item/group

### ISSUE THREAD

**Issue by Delerium** [Dynious/RefinedRelocation#342]
This suggestion is an extension of Issue #317.
Sorting could be extended to be more powerful by adding an optional weighted value on whitelisted items/groups that would override the container's default weighted value.  

Example of case use:
Chest 1 has a high weighted value, and has a broad filter of "Building Blocks" set, and contains cobblestone and gravel, etc.
Chest 2 has a normal weighted value, but you want a specific building block "Sand" in it, along with other items from other filters.
You would like these two cases to be true without altering the sorting weighted value of the rest of the chests contents.

**Comment by Dynious** [comment]
See #285, as it's quite similar This is something we plan on doing in 1.8, as our current API doesn't allow this system to work without breaking or becoming bad performance wise.
