### ISSUE TITLE
Crafting module is stacking unstackable items (back stuffing does this too)

### ISSUE THREAD

**Issue by Nonsanity** [Dynious/RefinedRelocation#345]
If not set to a stack size of 1, items that do not normally stack will stack inside a crafting module. If removed by hand or the module is broken, the stacked unstackable items can end up in the player's inventory. The contents released from a back-stuffed module can also create these stacks of unstackable items.

**Comment by Dynious** [comment]
The crafting module stacking has been fixed and the fix for stuffed stacking is coming!
