### ISSUE TITLE
Crafting Module's stack size button doesn't hold its value

### ISSUE THREAD

**Issue by Nonsanity** [Dynious/RefinedRelocation#346]
This seems to be more of a visual glitch, but when the stack size is changed in a crafting module's GUI and the GUI is closed and re-opened, the stack size can sometimes (more often than not in my tests) revert to the 64 default value. However, the module will still act as if its previous value is still set. Clicking the button will immediately set both the visual and actual value to the new setting, however.

**Comment by Dynious** [comment]
Thanks for reporting! Fix incoming!
