### ISSUE TITLE
Multi Module GUI Problem and Module Vanishes when Removed/Broken

### ISSUE THREAD

**Issue by Nonsanity** [Dynious/RefinedRelocation#349]
Once a Multi Module (with filter and extractor) starts being used (or possibly as soon as the inventory it is connected to is accessed by an extractor—even on attached to a different Relocator on another side—the GUI for the Multi Module shrinks down to just a few pixels wide and is unresponsive to clicks. Once this happens, it never seems to clear up again, making the settings for the other modules inaccessible.

Also, if the Module is removed, the other modules it holds are dropped but the Multi Module itself disappears. The same thing happens if the Relocator it is attached to is broken or the inventory it is next to is removed.

[Side note: It seems all the item flows are push-based instead of pull. So a common combination of modules I've found myself using over and over is an extractor combined with a filter set to the item(s) already in the chest. This prevents foreign items from entering the chest, but allows excess items from the chest to return to it instead of getting jammed somewhere else. This might be an idea for another module, reducing the need for the Multi Module somewhat.]

**Comment by blay09** [comment]
The multi module not being dropped itself is already fixed, just not released yet.

I plan to rewrite the multi module GUI this weekend (see #315) so the other issue will probably fix itself by then.

**Comment by Dynious** [comment]
The GUI problem has also already been fixed, but a list would be better :)
