### ISSUE TITLE
Unify tooltip style

### ISSUE THREAD

**Issue by Dynious** [Dynious/RefinedRelocation#350]
Block Extenders and Buffers have a shift to open tooltip.
Relocator modules, sorting upgrades and toolboxes have always open tooltips.
Power Limiter, Player Relocator etc. have no tooltip.

We need one style, should we do shift to open or always open?

**Comment by blay09** [comment]
I personally prefer the shit-click ones as they don't clutter the screen with big tooltips when there's more than one line (see Module Blocked Extraction for example).

I'd also go for the colors used in the Shift-to-open ones, because they look cool.

**Comment by Dynious** [comment]
Agree and agree. Okey!
