### ISSUE TITLE
Per filter white/black list option problems

### ISSUE THREAD

**Issue by Dynious** [Dynious/RefinedRelocation#354]
I have a few problems with the per filter white and blacklisting.
1. I don't know what has a higher priority, does blacklist override whitelist or the other way around?
2. It's no longer clear how to make an 'other items' inventory, a place where items go when there's no better place to go
3. I'm getting confused by this and I'm a developer, I guess players will get very confused

EDIT: After looking into the implementation it seems like 88471f23464cb6b0576f0414f7bff38cbce1ecb6 doesn't fix #317 at all. It just looks at the first filter where it finds a match and uses the setting there.

**Comment by blay09** [comment]
1. I suggest we make filter order define the priority? So blacklist on the top is overriden by whitelist, where as whitelist on the top is overriden by blacklist. Could mention that in the tooltip for the button.

2. Still the same way as before, what about that has changed? If you just use one filter you'll also just have one blacklist/whitelist button.

**Comment by blay09** [comment]
Alright, so now it goes through the filters from top to bottom, and basically a filter at the bottom overrides a filter at the top. So you could create one filter to whitelist all ingots, then put one after that blacklists gold ingots, and you'll have all ingots but gold pass.

I've also added this as a note to the tooltip of the blacklist/whitelist button.
