### ISSUE TITLE
1.0.8b - Multi Module broken GUI and not dropping when broken

### ISSUE THREAD

**Issue by InvaderAZ** [Dynious/RefinedRelocation#355]
I crafted the Multi Module and stuck it on a pipe with a filter and extraction module.  I would right click the Multi Module and get prompted with 2 buttons for which of the other modules to config.  Everything looks great and I filter what I want extracted, system works fine.

I walk away, decide I want to add another filter, but when I go back to the multi module and right click there is no longer the prompt with the 2 buttons, it's just a small white spot in the center of the screen where the cursor would be.  I shift right click the relocator to return the modules, and I only get back the Extract and Filter, the Multi module is just gone.

Now I'm running a custom modpack with a bunch of mods, but for sanity sake I created a separate instance with just CCC, NEI, and RefinedRelocation and the results are the same.

Video of opening the Multi Module UI resulting in a small white spot in the center by the cursor, and of attempting to remove all 3 modules and only getting back 2.

https://youtu.be/BprzsZ6G574

**Comment by blay09** [comment]
Was fixed in #349, just not released yet.
