### ISSUE TITLE
[1.0.8b] Easy dupe items system

### ISSUE THREAD

**Issue by nmakoto** [Dynious/RefinedRelocation#358]
One chest, one sorting interface, one module extraction and two relocators.
Interface must be connected to the chest. Place any item in chest and u will get double of it... and so on.

![2015-09-21_14 59 03](https://cloud.githubusercontent.com/assets/183187/9989525/99ec48d6-6072-11e5-84f6-6bdebb064324.jpg)

**Comment by blay09** [comment]
Fixed in #304
