### ISSUE TITLE
Disconnected from server on opening sorting chest filter GUI

### ISSUE THREAD

**Issue by BBoldt** [Dynious/RefinedRelocation#366]
* RefinedRelocation-mc1.7.10-1.1.4
* forge 1492

<Unabridged> Redwuff: If anyone sees BBolt again in IRC, tail of the only log that updated when I got dumped by entering the Filter UI of a sorting chest is here: http://pastebin.com/649GKv2u

**Comment by blay09** [comment]
Is this a reproduceable problem? Having checked the code, this is something I don't have any influence on; for some reason the client received a nonsensical value that was definitely not the one that was sent. Either the FML network wrapper or Netty somehow messed up, or the network connection was possessed by demons.

**Comment by BBoldt** [comment]
Actually, I can't reproduce it myself. Just tried. 

Sorry, I was just making a report for someone else who was complaining to me in IRC about the RR update messing stuff up.

I just remembered they are running a kcauldron server, so it probably has something to do with that.

* KCauldron-1.7.10-1481.148

http://tcpr.ca/kcauldron

**Comment by BBoldt** [comment]
getting more info now, trying to get someone on their server to try and reproduce the issue again

**Comment by BBoldt** [comment]
Scratch all of what I said above, it's nothing to do with cauldron and I am able to reproduce it easily.

**Comment by BBoldt** [comment]
Open sorting chest gui --> click on the tab with the "C" on it --> disconnect

```
31<BBoldt>30 can someone on Unabridged right now do me a favor?
18<26Unabridged> YuBh8Tn: Depends, bbold
31<BBoldt>30 craft a "sorting chest" and shift + right click it
18<26Unabridged> YuBh8Tn: I'm on Unabridged
18<26Unabridged> YuBh8Tn: Okay gimme a sec
21<Unabridged>21 YuBh8Tn: BBoldt, I did that, now what?
18<26Unabridged> YuBh8Tn: A screen showed up
31<BBoldt>30 any problems with the screen or gui or anything like that?
18<26Unabridged> [YuBh8Tn disconnected]
18<26Unabridged> Mini_Hermit: well he just crashed.,..
31<BBoldt>30 okay
18<26Unabridged> [YuBh8Tn connected]
18<26Unabridged> YuBh8Tn: yep.
18<26Unabridged> YuBh8Tn: lol
18<26Unabridged> YuBh8Tn: It crashed me
18<26Unabridged> [YuBh8Tn disconnected]
31<BBoldt>30 what did you click on to result in the disconnect?
18<26Unabridged> YuBh8Tn: Something with a big C and it said something like "Creative..."
18<26Unabridged> YuBh8Tn: Crashed before I could read it
18<26Unabridged> YuBh8Tn: I can't even normally open the chest without crashing anymore
31<BBoldt>30 okay
18<26Unabridged> YuBh8Tn: I mean the screen
31<BBoldt>30 confirmed
18<26Unabridged> [YuBh8Tn disconnected]
18<26Unabridged> [YuBh8Tn connected]
31<BBoldt>30 thanks for the help
```

**Comment by BBoldt** [comment]
ha, it even happens in singleplayer "this connection is terminated"

wat

**Comment by blay09** [comment]
I'm an idiot
