### ISSUE TITLE
Filters don't seem to be entirely working in 1.1.10

### ISSUE THREAD

**Issue by toticorrea** [Dynious/RefinedRelocation#369]
Hi. Me again. Refering to the same issue from the 1.1.4. I just installed the 1.1.10 and still have problems with the filters. It seems that can´t recognize the custom filters with commas. (now with line breacks). All chests wich I had filters with more than 1 item separated with commas in the old version, can´t be sorted in this version.
But also I have another strange issue of this type that I still can´t figure it out why. I have a chest sorted only with *stairs, no commas, nothing. And this one also can´t recognize. All the stairs are going to another chest with no filters Maybe the * is the problem?
Also I have a furnace connected with a wireless block extender with a extraction module with no filter. Some items (food) goes out, others do not (stone).
Last time (in the 1.1.4) in the same furnace I noticed that the coal werent getting in from a chest. Now this is solved.

**Comment by toticorrea** [comment]
More data. The filetrs that were changed the commas with line breacks in this version and were not working, I put the commas again, deleted the line breack, and they work properly again.
Still can´t solved the * problem

**Comment by TruePikachu** [comment]
I can confirm. Also just got a hung UI when I was trying to remove a comma at the end of a line (which might have been accepting everything? can't confirm), but the filter issue takes priority.

**Comment by AnimeniacYuuto** [comment]
In addition i've gotten a crash when adding a Mod Filter.

https://www.dropbox.com/s/dkm7bltap2loltl/crash-2015-10-22_22.59.54-client.txt?dl=0

**Comment by blay09** [comment]
Thanks for the feedback; I'll get onto fixing the issues as soon as I can.

I've split this one up into the several sub issues. It makes it easier to get an overview without having to read through everything again and again.
