### ISSUE TITLE
Sorting with Iron Chests on Server

### ISSUE THREAD

**Issue by awkwaRdcaRRot** [Dynious/RefinedRelocation#376]
Was trying to set up a simple sorting system, started with 3 Copper chests and 1 Iron chest. After disconnecting and relogging, chests no longer sorted to their proper chest, just stayed in the dump chest.

**Comment by GauHelldragon** [comment]
I am also having this problem. I am using several diamond and iron chests, a regular sorting chest, and a few sorting barrels. The sorting network seems to become broken after disconnect/relog and possibly when the chunk is unloaded. 

The only way to get everything sorting again is to break/replace all the barrels and chests, or move them with jabba dolly

**Comment by torndar** [comment]
I'm also having this issue. I can provide a world download if that would help with troubleshooting, or just let me know what else I can do to help figure this one out.

**Comment by blay09** [comment]
I can't reproduce this issue. I tried this simple setup on a server and client.

Left Sorting Chest (dump chest): NORMAL-LOW priority, no filters
Right Sorting Chest (target chest): NORMAL-HIGH priority, Creative Tab Filter

I've tried relogging and unloading the chunk, it kept working as it should.

![2016-01-24_08 28 58](https://cloud.githubusercontent.com/assets/1933180/12535027/9b56900a-c274-11e5-8583-465fa787084f.png)

**Comment by CAHenson** [comment]
This issue is occurring on my server of 2 people with only 1 sorting system.
After a time, the chests just stop sorting entirely, JABBA dolly replacement fixes it for now but it's really frustrating. I believe it might have something to do with the chests accepting items from the re-locator pipes. E.G: Using pipes from a regular to chest to sorting iron chests after a while possibly breaks them.

**Comment by blay09** [comment]
I've made an attempt to fix this. I'm still not sure why it's happening and I have no idea if the change will actually result in anything, but it's my best guess at the moment.

If anyone who's consistently experiencing the issue wants to see if they can still have it happen with this build, please do so: http://jenkins.blay09.net/job/Refined%20Relocation%201.7.10/22/
