### ISSUE TITLE
Crash using the toolbox

### ISSUE THREAD

**Issue by romanticjo** [Dynious/RefinedRelocation#378]
In Revolution Pack (ATLAuncher), using toolbox, tried to add some tools and crash. Any further startup crash attempting to render player hotbar (where the toolback is located).

I believe the tool I attempted to add is  rotarycraft screwdriver.  A previous tool (eio wrench) was successfully added.

Relevant stack trace:
https://gist.github.com/romanticjo/275cc70036847557ad40

ModPack version: 1.3.0 
Mod version: RefinedRelocation-1.7.10-1.0.8b-haggle1996.jar

**Comment by blay09** [comment]
This has already been fixed in the latest version, @Haggle1996 will need to update.
