### ISSUE TITLE
Items get void in relocatiors

### ISSUE THREAD

**Issue by quasarea** [Dynious/RefinedRelocation#379]
Hi, I'm playing singe in Galactic Science modpack. I tried to automate charcoal production with basic furnace by relocators, just basics. What I'm seeing is that every time there is a delay (no wood in chest) system get stuck and when wood is back in chest there are two options:
* no extraction
* extraction to void (wood travel across system but when hits furnace it disappears)
Thanks
J

**Comment by Melodeiro** [comment]
Same problem, wood not appearing in furnace, just disappearing from relocators. Playing the same "Galactic Science" modpack. I have this installation: Chest -> Relocator with extraction module -> relocator with filter module -> vanilla furnace. Charcoal sometimes disappearing too if i pull it to vanilla furnace, and sometimes don't want to extract. Sometimes this things works, sometimes not (after some of replacing relocators).

**Comment by quasarea** [comment]
I have updated this mod in modpack to current version and it seems to work fine now

**Comment by Melodeiro** [comment]
Oh, i thought 1.0.8 version is lastest, thanks.

**Comment by blay09** [comment]
I guess it's been fixed already, then.
