### ISSUE TITLE
Crash when placing Armourer's Workshop item into sorting system

### ISSUE THREAD

**Issue by Alaberti** [Dynious/RefinedRelocation#380]
While I was offline, my server crashed with this error: http://pastebin.com/1mmhv3eg

I don't have any specific details but it looks like a couple of issues happening at once. @RiskyKen, you might want to look at this as well.

**Comment by RiskyKen** [comment]
You already reported this on my issue tracker, it was an issue on my end. It has been fixed for the next build but I have been a bit too busy to put one out. (soon™)

https://github.com/RiskyKen/Armourers-Workshop/issues/72

**Comment by Alaberti** [comment]
...I'm so bad @RiskyKen sorry!
