### ISSUE TITLE
Custom sorting not working for Broken Ores

### ISSUE THREAD

**Issue by Sir-underscore** [Dynious/RefinedRelocation#383]
I am setting up a system for auto-ore making, and I have a sorting interface hooked up to a crafter set to "broken*" so that broken ores will go in and be crafted into ore gravel. For some reason, it doesn't sort them and they just stay in the same chest.

**Comment by blay09** [comment]
This could be two things:
1) A priority issue - the interface has a lower or equal priority to the chest containing the broken ores
2) Items get sorted as they enter an inventory - if they're already inside you'll need to take them out and put them back in.

I've tried to reproduce the issue and things worked fine for me.

**Comment by blay09** [comment]
#407
