### ISSUE TITLE
Text filter not working on server

### ISSUE THREAD

**Issue by Sir-Will** [Dynious/RefinedRelocation#385]
Version: RefinedRelocation-mc1.7.10-1.1.12

The text filter doesn't work in multiplayer only in singleplayer. The items just stay in the chest and don't get moved.

**Comment by blay09** [comment]
Are you playing with a language other than en_US in singleplayer? I'm pretty sure the server checks the english item names, so if you're using names from another language pack this might be why.

**Comment by SirWilli** [comment]
Nope, default language, so en_US
