### ISSUE TITLE
took me an hour to find this version...question!

### ISSUE THREAD

**Issue by Blue64** [Dynious/RefinedRelocation#386]
I have currently running in my mods folder on ```MC 1.7.10``` ```RefinedRelocation-mc1.7.10-1.1.13.jar``` yet the latest release I can seem to locate is ```mc1.7.10-1.1.12.jar```, so naturally, the first place I went snooping around for is your ```Jenkins``` Repository, but I have been unable to find it anywhere (normally I find it in under 5 min)...so...like...where is it man? I want to see what kind of stuff you've done lol

...wow, right idea, wrong name...but why didn't [it](http://jenkins.blay09.net/job/Refined%20Relocation/) show up when i searched? more importantly, what is the actual most up-to-date release for 1.7.10?

@blay09 you helped me solve this question with a really really really old post (like, 2~3 months), so thanks!

**Comment by blay09** [comment]
The latest version is the one on my Jenkins at http://jenkins.blay09.net/job/Refined%20Relocation/. It's linked on the CurseForge page (Development Versions).

**Comment by Blue64** [comment]
```*facepalm*``` the one place I never check, the ```CurseForge``` overview page. y'all are one of the few mods that doesn't just ```copy/paste``` their ```MinecraftForum``` post into their ```CurseForge```.

@blay09 Thanks for the quick response ```:)``` it's good to know that I've got the most up-to-date version ```:)``` (I last checked my mods over a month ago lol spent half the day searching)
