### ISSUE TITLE
Crash when destroying relocators

### ISSUE THREAD

**Issue by Ukelelechris** [Dynious/RefinedRelocation#387]
Reported this on the 1.7.10 pack and was directed here. Had an error that crashed the server

http://pastebin.com/ds7BwcQt

btw, I LOVE this mod. keep up the good work!

**Comment by blay09** [comment]
Looks like some weird issue caused by Forge Mutlipart's black magic. Does it always happen or was this a one time thing? Looking at the code I couldn't find anything wrong on our side.

**Comment by ericcotelnu** [comment]
Looks like my crash log, heh. I suspect forge too, not playing nice with RefRel

**Comment by ericcotelnu** [comment]
I found I get this when I'm breaking a relocator with a module present in it. A relocator on its own doesn't do this.

**Comment by b0bst3r** [comment]
http://pastebin.ubuntu.com/15742349/

Got a similar thing, breaking a relocator and not ones with modules in, they cause server to crash (with the attached crash).  It seems random as we are all into relocators, sometimes happening, sometimes not, 2 of the guys who experienced this have no FMP anywhere.

**Comment by luxifr** [comment]
me, too!
[crash-2016-07-17_13.15.14-server.txt](https://github.com/Dynious/RefinedRelocation/files/367892/crash-2016-07-17_13.15.14-server.txt)
[crash-2016-07-17_13.21.37-server.txt](https://github.com/Dynious/RefinedRelocation/files/367893/crash-2016-07-17_13.21.37-server.txt)

**Comment by MadEgg** [comment]
I have the same issue while destroying relocators without modules in them. I think this issue may need to be re-opened.
