### ISSUE TITLE
Incorrect "special characters" in text field for filter

### ISSUE THREAD

**Issue by addrever** [Dynious/RefinedRelocation#392]
Hello,

I, like a n00b, accidentally put a parenthesis in the text field and now it crashes the server every time I load the chunk.  Is there a way, without killing everything in the world that's refined relocation, to fix this?

This isn't really an issue, but more of an enhancement.  Something that would handle this exception?

I have attached the log file of the crash.
[logs.zip](https://github.com/Dynious/RefinedRelocation/files/175390/logs.zip)

Thanks for your time!

**Comment by blay09** [comment]
Are you running on the latest version? I'm pretty sure I fixed this issue a while back.

**Comment by addrever** [comment]
Version 1.1.21

**Comment by blay09** [comment]
Try this build, it should (hopefully) fix the issue: http://jenkins.blay09.net/job/Refined%20Relocation%201.7.10/26/

**Comment by addrever** [comment]
Worked!  Thanks a lot!
