### ISSUE TITLE
Sorting chests do not seem to work

### ISSUE THREAD

**Issue by MadEgg** [Dynious/RefinedRelocation#402]
In version 'RefinedRelocation-mc1.7.10-1.1.28.jar', the filters configured in sorting chests simply seem to be ignored.

I put in a text filter '!dustCoal' to allow only coal dust in, for example. However, wood, rubber, obsidian an all other kinds of stuff enter the chest anyway. I needed to add a filter module to the relocator connecting to the chest to resolve it, but that kind of defeats the purpose of the sorting chest in the first place.

Not sure if this mod is being updated anymore, seeing the long time since the last commit, but I'm reporting it anyway.

**Comment by blay09** [comment]
The chest filters in Refined Relocation aren't really filters, as in they won't actually prevent items from entering a chest. What they will do though is redirect items within the network, so if you have an input chest A that accepts everything, and a higher-priority chest B in the same network (adjacent or connected to each other using sorting connectors) that accepts !dustCoal, putting coal dust into the chest A will automatically redirect it to chest B.
