### ISSUE TITLE
Chests, extractors and crafting modules not working together -> clogged pipes

### ISSUE THREAD

**Issue by MadEgg** [Dynious/RefinedRelocation#403]
First of all, thanks for a very promising mod that has loads of very useful features and design ideas!

I have a storage system consisting of several Mekanism Ultimate Bins, and a system of machines and crafting modules producing new items for those bins.

It seems that extractors have a strong tendency to oversend, clogging pipes. The crafting modules are the first ones to get clogged: if one ingredient isn't supplied sufficient, the pipe leading up to it will clog with one of the other ingredients, preventing the correct ingredient from entering and thus stopping the entire process.

I thought that maybe the problem is that the bins extract from one side and insert from the other, so that extracted elements could not be re-inserted where they came from. The storage network has a separate insertion and extraction network, to prevent items from ejecting at the bottom of the bins just to re-enter the same bin at the top again.

In order to solve this, I added buffer chests in front of the crafting modules. Quite tedious, but anyway. I have one dedicated chest for each ingredient, so that they cannot get clogged by other ingredients.

At the other side of the chest, they get extracted again and lead to the crafting module. However, the system still clogs: items are ejected from the chest and lead to the crafting module. However, if that is full, they attempt to return to the chest they came from. It is very well possible that that chest was filled by newly produced items from the other side, so that the rejected items cannot re-enter the same chest. This will lead to clogging once again.

I understand that without the clogging, the items would need to pop out, which is one of the reasons I moved from Buildcraft pipes to Refined Relocators, but a much better solution would be just not to oversend all the time. It seems that if there's no valid target inventory, an extractor will not extract. If it does decide to extract, it should basically directly reserve the space in the target inventory, and not just wait and see if it will end up there and fill it. Because the way it currently happens is that if the pipe is long enough, hundreds of stacks of items may be underway to fill just one spot in an inventory. This requires very tedious fine tuning of the speed and stack size of the extractors, which is something I'd rather not do. It seems that logistical transporters from Mekanism do a way better job at this: i never had clogging pipes or items popping out. However, from those pipes I'm missing the flexibility that the sorting filters in Refined Relocation (or diamond pipes in buildcraft) give me.

No clue if this mod is being maintained at all, seeing that the latest update it quite a while ago, but I'm reporting this in case anyone feels like improving on the mod.

This issue, combined with the rather annoying issue that the server will regularly completely crash (issue #387) when destroying relocators, is driving me away from these relocators, unfortunately.

**Comment by blay09** [comment]
Changes to how clogging works were discussed in the past, but would require major changes in how they work currently. Given that 1.7.10 is (or should be) dead at this point, this unfortunately won't be seeing a fix.

As of now there's also no plans to re-introduce relocators in the 1.10.2 version.
