### ISSUE TITLE
Weird rendering

### ISSUE THREAD

**Issue by davqvist** [Dynious/RefinedRelocation#406]
Refined Relocation 2.1.18
Minecraft 1.10.2

So when placing down Refined Relocation Chests, they have a weird black rendering. Hard to explain, look at that picture: http://i.imgur.com/FERRv8O.png

If you need more info, let me know.

**Comment by blay09** [comment]
Are you using any mods that mess with rendering, such as OptiFine?

**Comment by davqvist** [comment]
No Optifine, no specific mods that mess with rendering that I know of.
