### ISSUE TITLE
Wheat just doesn't sort

### ISSUE THREAD

**Issue by J4YD3D** [Dynious/RefinedRelocation#410]
Im using the "unabridged" modpack, so perhaps its some id issue or something, but when using a few chests in a line, and pumping items from another chest off of the sorting network, wheat always fails to go in any chest BUT the one closest to the output of the pipe. Wheat is the only thing I've had do this so far, even if i have highest priority on other chests, and they're sorted to only allow wheat, and the closest chest has wheat blacklisted, it still goes in that chest over an empty chest set to take that item
 **EDIT**
 Upon further inspection it seems that anything in the "materials" tab of minecraft just doesn't sort properly. im not aware if youve already fixed this for a later version, and the modpack im playing has just neglected to update so far, but it's extremely aggravating. Thanks for any response!
**FURTHER EDIT**
it seems that if i use my inventory sorting client side mod, it forces some update, that the chest w/ the materials tab picks up on, but only with some items? im confused as to if its working or not now, and then grabs those items. maybe bad compatibility between the two mods, on either mod's part.
**Sorry for so many edits**
there seems to be the issue of if youve got multiple chests in a line, say 100 or more, after a few chests, the items get sorted to an adjacent chest rather than the chest with that mod filter. Example: i have a crap ton of chests. the top row (each row is four) is half normal minecraft tabs (creative tab sorting style) and the last one is "witching gadgets" when i put witching gadgets items in that chest, it instead pops into the next available chest "right" of it, the first chest in the second row. perhaps this is the actual issue and not the id like i thought earlier, but either way, i wished to bring it to your attention. thank you once again for a response and also making this mod in general its an amazing mod and i doubt i could code anything like it in my life

**Comment by blay09** [comment]
Not sure what's the cause of this, but it seems to be an isolated case and 1.7.10 is pretty much dead at this point, so this probably won't be getting fixed.
