### ISSUE TITLE
Easy item duplication with "Barrels, Drums, Storage and More"

### ISSUE THREAD

**Issue by twothe** [Dynious/RefinedRelocation#414]
Using Refined Relocation 1.12.2-4.2.36 with "Barrels, Drums, Storage and More" 0.0.24 on Forge 2847.

When putting a Block Extender on a Crate from the BDSaM mod then removing the Block Extender again with a pick axe, it will not only drop the Block Extender but also the entire storage of the Crate without removing a single item from the Crate.

This is a very easy way to duplicate any item in the game in large quantities.

**Comment by BlayTheNinth** [comment]
Moved to https://github.com/blay09/RefinedRelocation2/issues/75
